name: Deploy bot
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    deploy:
        name: Deploy bot
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

            - name: Setup Node.JS
              uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
              with:
                  node-version-file: package.json
                  cache: npm

            - name: Install
              run: npm ci --force

            - name: Deploy
              run:
                  npx railway up --ci --service 4560c924-5c5c-41fe-8854-f484428ed753 --environment
                  production
              env:
                  RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
