name: Deploy bot
on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    deploy:
        name: Deploy bot
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

            - name: Setup Node.JS
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
              with:
                  node-version-file: package.json
                  cache: npm

            - name: Install
              run: npm ci --force

            - name: Deploy
              run:
                  npx railway up --ci --service 4560c924-5c5c-41fe-8854-f484428ed753 --environment
                  production
              env:
                  RAILWAY_TOKEN: ${{secrets.RAILWAY_TOKEN}}
