name: Lint
on:
    push:
    pull_request_target:
    workflow_dispatch:

permissions: write-all

jobs:
    format:
        name: Format
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  token: ${{secrets.TOKEN || secrets.GITHUB_TOKEN}}
                  ref: ${{github.head_ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}

            - name: Setup Node.JS
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version-file: package.json
                  cache: npm

            - name: Install
              run: npm ci

            - name: Format
              run: node --run format

            - name: Assert clean
              if: startsWith(github.ref_name, 'dependabot/') == true
              run: if [[ `git status --porcelain` ]]; then exit 1; fi

            - name: Commit
              uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
              with:
                  commit_message: Format

    analyze:
        name: Analyze
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  ref: ${{github.head_ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}

            - name: Setup CodeQL
              uses: github/codeql-action/init@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
              with:
                  languages: javascript
                  queries: security-and-quality

            - name: Analyze
              uses: github/codeql-action/analyze@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1

    build:
        name: Build & Test
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  ref: ${{github.head_ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}

            - name: Setup Node.JS
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version-file: package.json
                  cache: npm

            - name: Install
              run: npm ci

            - name: Build & Test
              run: node --run test

    lint:
        name: Lint
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  ref: ${{github.head_ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}

            - name: Setup Node.JS
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
              with:
                  node-version-file: package.json
                  cache: npm

            - name: Install
              run: npm ci

            - name: Lint
              run: node --run lint
